server:
  port: 8081
  error:
    include-message=always
    include-binding-errors=always
    include-exception=true

spring:
  profiles:
    active: dev

  mvc:
    throw-exception-if-no-handler-found=true
  web:
    resources:
      add-mappings=false

  shell:
    interactive:
      enabled: true
    script:
      enabled: true

  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,templates/**

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/saas_erp_cash_mgt_pdb_ac
    username: saas_erp_cash_mgt_pdb_ac_adm
    password: saas_erp_cash_mgt_pdb_ac_adm_352415300399
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracle.ucp:
      connection-pool-name: connectionPoolName1
      initial-pool-size: 1
      min-pool-size: 1
      max-pool-size: 2
      connection-factory-class-name: oracle.jdbc.pool.OracleConnectionPoolDataSource

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      ddl-auto: create
    show-sql: true

  liquibase:
    enabled: false
    change-log: classpath:database/changelog/db.changelog-master.yml

management:
  health:
    probes:
      enabled: true

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE

hibernate:
  transaction:
    jta:
      platform: org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform
